---
- name: check mandatory variables
  ansible.builtin.assert:
    that:
      - docker_container_image is defined
    quiet: true

- name: build docker image
  community.docker.docker_image:
    source: build
    name: "{{ docker_container_image }}"
    force_source: true
    build:
      path: "{{ docker_container_build_path }}"
      dockerfile: "{{ docker_container_build_dockerfile_path | default(omit) }}"
      network: "{{ docker_container_build_network | default(omit) }}"
      args: "{{ docker_container_build_args | default(omit) }}"
  when: docker_container_build_path is defined

- name: run docker container
  community.docker.docker_container:
    name: "{{ docker_container_name }}"
    image: "{{ docker_container_image }}"
    entrypoint: "{{ docker_container_entrypoint | default(omit) }}"
    command: "{{ docker_container_command | default(omit) }}"
    env: "{{ docker_container_enviroments | default(omit) }}"
    network_mode: "{{ docker_container_network | default(omit) }}"
    published_ports: "{{ docker_container_ports | default(omit) }}"
    labels: "{{ docker_container_labels | default(omit) }}"
    restart_policy: "{{ docker_container_temporary | ternary('no', 'unless-stopped', omit) }}"
    privileged: false
    recreate: true
    force_kill: true
    detach: "{{ not docker_container_temporary }}"
    cleanup: "{{ docker_container_temporary }}"
  when: docker_container_name is defined
